### ISSUE TITLE
Breaking changes with typst 0.1.0 release

### ISSUE THREAD

**Issue by DeveloperPaul123** [lvignoli/typst-action#1]
Typst just released [0.1.0](https://github.com/typst/typst/releases/tag/v0.1.0) which breaks this github action due to the breaking changes in the `CLI`.

**Comment by lvignoli** [comment]
Thanks @DeveloperPaul123 ! It should be fixed now with c2fa81b7, could you confirm?

**Comment by DeveloperPaul123** [comment]
Yup! seems to have been fixed, thanks for the quick patch!

**Comment by lvignoli** [comment]
Great!
